### PR TITLE
Fix kohi and vanilla knockback configs

### LINKED ISSUE #52: Weird knockback
**Describe the bug**
Knockback is different from NachoSpigot. Players are complaining about him. NachoSpigot had no problem.

**Bug on latest**
Yes

### PR DESCRIPTION
**Pull request by ghost**
Fixes #52

### CODE REVIEW

File: WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java [hunk 1]
```diff
@@ -45,8 +45,8 @@ public static void init(File configFile) {
 
 		Set<String> keys = getKeys("knockback.profiles");
 		
-		if (!keys.contains("kohi")) {
-			final KnockbackProfile kohiProfile = new CraftKnockbackProfile("kohi");
+		if (!keys.contains("vanilla")) {
+			final KnockbackProfile kohiProfile = new CraftKnockbackProfile("vanilla");
```
Comment (windcolor-dev) [inline WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java]:
```suggestion
			final KnockbackProfile vanillaProfile = new CraftKnockbackProfile("vanilla");
```

File: WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java [hunk 2]
```diff
@@ -45,8 +45,8 @@ public static void init(File configFile) {
...
 			kohiProfile.save(true);
```
Comment (windcolor-dev) [inline WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java]:
```suggestion
			vanillaProfile.save(true);
```

File: WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java [hunk 3]
```diff
@@ -68,11 +68,25 @@ public static void init(File configFile) {
...
+		if (!keys.contains("kohi")) {
+			final KnockbackProfile defaultProfile = new CraftKnockbackProfile("kohi"); 
+
+			defaultProfile.setHorizontal(0.35);
+                        defaultProfile.setRodHorizontal(0.35);
+                        defaultProfile.setArrowHorizontal(0.35);
+                        defaultProfile.setPearlHorizontal(0.35);
+                        defaultProfile.setSnowballHorizontal(0.35);
+                        defaultProfile.setEggHorizontal(0.35);
+                        defaultProfile.setAddHotizontal(0.425);
```
Comment (windcolor-dev) [inline WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java]:
```suggestion
                        defaultProfile.setExtraHorizontal(0.425);
```

File: WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java [hunk 4]
```diff
@@ -68,11 +68,25 @@ public static void init(File configFile) {
...
+
+			defaultProfile.setVertical(0.35);
+                        defaultProfile.setRodVertical(0.35);
+                        defaultProfile.setArrowVertical(0.35);
+                        defaultProfile.setPearlVertical(0.35);
+                        defaultProfile.setSnowballVertical(0.35);
+                        defaultProfile.setEggVertical(0.35);
+                        defaultProfile.setAddVertical(0.085);
```
Comment (windcolor-dev) [inline WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java]:
```suggestion
                        defaultProfile.setExtraVertical(0.425);
```
Add vertical is actually added to knockback, extra vertical is the additional knockback multiplier for player entities.

File: WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java (hunk 3 above)
Comment (ghost) [reply WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java]: ~~It’s addHorizontal, I just spelt it wrong~~ Nevermind
```suggestion
                        defaultProfile.setAddHorizontal(0.425);
```

Comment (windcolor-dev) [reply WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java]: Add horizontal is different from extra horizontal, add horizontal is added to knockback, and extra horizontal is the knockback multiplier for players' knockback. Add horizontal is an option added by WindSpigot, so did you mean to use the other method?

Comment (ghost) [reply WindSpigot-Server/src/main/java/ga/windpvp/windspigot/knockback/KnockbackConfig.java]: I used addHorizontal/Vertical because I didn’t see extraHorizontal/Vertical and I thought it was renamed :P

**Comment by windcolor-dev** [comment]
This LGTM, have you done any in game testing to ensure the values are accurate?

**Comment by ghost** [comment]
Haven’t tested it however I got the values from https://github.com/CobbleSword/NachoSpigot/pull/174 and I checked the kohi values with the original kohi gist and they are the same, so it should be accurate.

**Comment by windcolor-dev** [comment]
Ok, thanks for this PR :)
